config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'materials/index'
  get 'materials/new'
  resources :todos
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :limit)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="py-4 bg-yellow-200 sm:bg-green-300 md:bg-violet-400 lg:bg-orange-400 w-full mt-0">
<div class="container mx-auto flex justify-between items-center px-8 ">

<h1 class="text-2xl font-bold hover:text-white transition-all duration-300 whitespace-nowrap">Material App</h1>

<div class="hidden md:flex">
<ul class="flex justify-between  sm:space-x-1 md:space-x-4  items-center white space-nowrap">
<li class="hover:text-white transition-all duration-300 list-none "><%= link_to '材料一覧', '/static_pages/home' %></li>
<li class="hover:text-white transition-all duration-300"><%= link_to '材料追加', '/static_pages/about' %></li>
<li class="hover:text-white transition-all duration-300 list-none"><%= link_to 'ログイン', '#' %></li>
<li class="hover:text-white transition-all duration-300 list-none"><%= link_to 'ログアウト', '#' %></li>
<li class="text-white px-6 py-2 bg-blue-400 font-bold rounded-lg hover:bg-blue-300"><%= link_to 'お問い合わせ', '#' %></li>
</ul>
</div>

<div class="md:hidden">
  <i class="fa-solid fa-bars"></i>
</div>
</div>

<div>
  <ul class="px-16 py-4 hidden">
    <li class="px-8 py-2 text-white hover:bg-gray-600 my-4 rounded-md border-b"><a href="#">機能一覧</a></li>
    <li class="px-8 py-2 text-white hover:bg-gray-600 my-4 rounded-md border-b"><a href="#">料金プラン</a></li>
    <li class="px-8 py-2 text-white hover:bg-gray-600 my-4 rounded-md border-b"><a href="#">HRとは</a></li>
    <li class="px-8 py-2 text-white hover:bg-gray-600 my-4 rounded-md border-b"><a href="#">お知らせ</a></li>
    <li class="px-8 py-2 text-white hover:bg-gray-600 my-4 rounded-md border-b"><a href="#">お問い合わせ</a></li>
  </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaterialApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/destyle.css@1.0.15/destyle.css"/>
    
  </head>
"
  <body class="bg-black">
  <%= render 'layouts/header' %>
  <%= yield %>
  </body>
</html>

app/views/materials/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Materials#index</h1>
  <p>Find me in app/views/materials/index.html.erb</p>
</div>

app/views/materials/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Materials#new</h1>
  <p>Find me in app/views/materials/new.html.erb</p>
</div>

app/views/static_pages/help.html.erb
<div class="container mx-auto mt-24 bg-blue-200">
<div class="flex flex-start space-x-8 pt-4 px-4">
<a class="hover:text-red-400 transition-all duration-300 ">Trending</a>
<a class="hover:text-red-400 transition-all duration-300 ">Articles</a>
<a class="hover:text-red-400 transition-all duration-300 ">Books</a>
<a class="hover:text-red-400 transition-all duration-300 ">Scraps</a>

</div>
<h1 class="font-bold text-4xl pl-20 py-8 ">Tech</h1>
<div class="grid grid-cols-2 ">

  <div class="mx-auto flex bg-blue-200 mb-8">

    <div class="w-20 h-20 bg-white rounded-lg">
      <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-16 h-16 mx-auto mt-2" %>
    </div>
    
    <div class="mt-2 pl-2">
      <p class="text-neutral-600">atomsで活用したいCSS隣接セレクタ</p>

      <div class="mt-3">  
        <div class="flex">
          <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-8 h-8 " %>
        <p class="mb-4 pl-2 text-neutral-600">Takepepe<br>1日前・3min read <i class="fa-solid fa-heart">33</i></p>
        </div>

      </div>
    </div>

  </div>
  <div class="mx-auto flex bg-blue-200 mb-8">

    <div class="w-20 h-20 bg-white rounded-lg">
      <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-16 h-16 mx-auto mt-2" %>
    </div>
    
    <div class="mt-2 pl-2">
      <p class="text-neutral-600">atomsで活用したいCSS隣接セレクタ</p>

      <div class="mt-3">  
        <div class="flex">
          <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-8 h-8 " %>
        <p class="mb-4 pl-2 text-neutral-600">Takepepe<br>1日前・3min read <i class="fa-solid fa-heart">33</i></p>
        </div>

      </div>
    </div>

  </div>
  <div class="mx-auto flex bg-blue-200 mb-8">

    <div class="w-20 h-20 bg-white rounded-lg">
      <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-16 h-16 mx-auto mt-2" %>
    </div>
    
    <div class="mt-2 pl-2">
      <p class="text-neutral-600">atomsで活用したいCSS隣接セレクタ</p>

      <div class="mt-3">  
        <div class="flex">
          <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-8 h-8 " %>
        <p class="mb-4 pl-2 text-neutral-600">Takepepe<br>1日前・3min read <i class="fa-solid fa-heart">33</i></p>
        </div>

      </div>
    </div>

  </div>
  <div class="mx-auto flex bg-blue-200 mb-8">

    <div class="w-20 h-20 bg-white rounded-lg">
      <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-16 h-16 mx-auto mt-2" %>
    </div>
    
    <div class="mt-2 pl-2">
      <p class="text-neutral-600">atomsで活用したいCSS隣接セレクタ</p>

      <div class="mt-3">  
        <div class="flex">
          <%= image_tag 'banana',class:"object-cover rounded-md cursor-pointer w-8 h-8 " %>
        <p class="mb-4 pl-2 text-neutral-600">Takepepe<br>1日前・3min read <i class="fa-solid fa-heart">33</i></p>
        </div>

      </div>
    </div>

  </div>


  

</div>
</div>



  <div class="grid grid-cols-1 gap-8 text-center md:grid-cols-2 mt-16">
    <div class="bg-yellow-300 col-span-1 py-4 w-96 mx-auto ">
      <h1>Hello</h1>
    </div>
    <div class="bg-blue-200 col-span-1 py-4  w-96 mx-auto">
      <h1>Good Night</h1>
    </div>
    <div class="bg-red-200 col-span-1 py-4  w-96 mx-auto">
      <h1>Good Night</h1>
    </div>
    <div class="bg-green-200 col-span-1 py-4  w-96 mx-auto">
      <h1>Good Night</h1>
    </div>
  </div>

app/views/static_pages/home.html.erb
<div class="container mt-16 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">

  <div class="flex flex-wrap md:flex-nowrap">
    <div class="md:my-36 lg:ml-20 justify-center md:justify-start max-w-xl flex-wrap flex">
      <h1 class="text-white font-bold text-5xl text-center md:text-left lg:text-7xl md:text-6xl">TailwindCSSで<br>美しいサイトを<br>作ります
      </h1>
      <button class="text-white px-6 py-4 mt-10 bg-blue-400 font-bold rounded-lg hover:bg-blue-300">
        <i class="fa-solid fa-rocket"></i>
        <span>もっと見る</span>
      </button>
    </div>
    <div class="md:absolute lg:top-2 lg:right-52 md:w-3/5 w-10/12 mt-12 md:mt-0 right-6 mx-auto -z-10 lg:w-3/6">
      <%= image_tag 'human.jpg' %>
    </div>
  </div>
</div>

<div class="container mt-64 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">
  <section class="w-full">
    <h2 class="secondary-title">私のポートフォリオ</h2>
    <p class="section-paragraph">私が作ってきたWebアプリケーションはこちら</p>

    <div class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-6">
      <%= image_tag 'portfolio1.jpg',class:"w-full h-40 object-cover rounded-md cursor-pointer" %>
      <%= image_tag 'portfolio2.jpg',class:"w-full h-40 object-cover rounded-md cursor-pointer" %>
      <%= image_tag 'portfolio3.jpg',class:"w-full h-40 object-cover rounded-md cursor-pointer" %>
      <%= image_tag 'portfolio4.jpg',class:"w-full h-40 object-cover rounded-md cursor-pointer" %>
      <%= image_tag 'portfolio5.jpg',class:"w-full h-40 object-cover rounded-md cursor-pointer" %>
      <%= image_tag 'portfolio6.jpg',class:"w-full h-40 object-cover rounded-md cursor-pointer" %>
    </div>
  </section>
</div>

<div class="container mt-64 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">


  <section class="w-full">
    <h2 class="secondary-title">スキルスタック</h2>
    <p class="section-paragraph">以下のプログラミング言語を１年以上扱っています</p>

    <div class="my-16">
      <div class="w-full border border-purple-300 p-16 lg:px-32 lg:py-20 flex justify-center lg:justify-start flex-wrap lg:flex-nowrap lg:space-x-32 hover:border-yellow-300 transition-all duration-300 cursor-pointer">
        <div class="mb-6 lg:mb-0 self-center">
          <i class="fa-brands fa-js text-yellow-300 text-8xl"></i>
        </div>
        <div class="text-white text-center flex flex-wrap justify-center lg:text-left lg:block">
          <h3 class="text-3xl font-semibold">JavsScript</h3>
          <div class="flex flex-wrap w-full justify-center gap-3 lg:w-auto lg:justify-start mt-6 mb-8">
          <div class="badge">ウェブサイト制作</div>
          <div class="badge">フロントエンド開発</div>
          </div>
          <p class="text-secondary">JavsScriptエンジニア。普段はReactを使って働いています </p>
        </div>
      </div>

    </div>
    <div class="my-16">
      <div class="w-full border border-purple-300 p-16 lg:px-32 lg:py-20 flex justify-center lg:justify-start flex-wrap lg:flex-nowrap lg:space-x-32 hover:border-yellow-300 transition-all duration-300 cursor-pointer">
        <div class="mb-6 lg:mb-0 self-center"> 
          <i class="fa-brands fa-html5 text-orange-600 text-8xl "></i>
        </div>
        <div class="text-white text-center flex flex-wrap justify-center lg:text-left lg:block">
          <h3 class="text-3xl font-semibold">HTML/CSS</h3>
          <div class="flex flex-wrap w-full justify-center gap-3 lg:w-auto lg:justify-start mt-6 mb-8">
          <div class="badge">ウェブサイト制作</div>
          <div class="badge">フロントエンド開発</div>
          </div>
          <p class="text-secondary">JavsScriptエンジニア。普段はReactを使って働いています </p>
        </div>
      </div>

    </div>
    <div class="my-16">
      <div class="w-full border border-purple-300 p-16 lg:px-32 lg:py-20 flex justify-center lg:justify-start flex-wrap lg:flex-nowrap  lg:space-x-32 hover:border-blue-300 transition-all duration-300 cursor-pointer">
        <div class="mb-6 lg:mb-0 self-center">
          <i class="fa-brands fa-python text-blue-300 text-8xl"></i>
        </div>
        <div class="text-white text-center flex flex-wrap justify-center lg:text-left lg:block">
          <h3 class="text-3xl font-semibold">Python</h3>
          <div class="flex flex-wrap w-full justify-center gap-3 lg:w-auto lg:justify-start mt-6 mb-8">
          <div class="badge">ウェブサイト制作</div>
          <div class="badge">フロントエンド開発</div>
          </div>
          <p class="text-secondary">JavsScriptエンジニア。普段はReactを使って働いています </p>
        </div>
      </div>
    </div>
  </section>
</div>

<div class="container mt-48 mb-20 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">

<section class="w-full">
    <h2 class="secondary-title">お問合せ</h2>
    <p class="section-paragraph">私の経歴が気になる方はご一報ください</p>

    <div class="w-full grid lg:grid-cols-2 gap-8 lg:gap-32 mt-16">
      <div class="space-y-12">
        <div>
          <label class="text-white block mb-6 text-xl font-bold">お名前</label>
          <input type="text" class="w-full border border-inputBorder bg-input px-4 py-4">
        </div>
        <div>
          <label class="text-white block mb-6 text-xl font-bold">メールアドレス</label>
          <input type="text" class="w-full border border-inputBorder bg-input px-4 py-4">
        </div>
        <div>
          <label class="text-white block mb-6 text-xl font-bold">メッセージ</label>
          <input type="text" class="w-full border border-inputBorder bg-input px-4 py-4">
        </div>
        <button class="text-white px-8 py-3 mt-10 bg-blue-400 font-bold rounded-lg hover:bg-blue-300">
          送信する
        </button>
      </div>
      <div>
      <p class="text-secondary">000-1111-2222</p>
      <a href="mailto:katogen190@gmail.com" class="text-white">katogen190@gmail.com</a>

      <div class="mt-20 space-x-6">
        <a href="#">
          <i class="fa-brands fa-twitter text-3xl text-sky-400"></i>
        </a>
        <a href="#">
          <i class="fa-brands fa-facebook text-3xl text-sky-400"></i>
        </a>
        <a href="#">
          <i class="fa-brands fa-instagram text-3xl text-pink-400"></i>
        </a>
      </div>
      </div>
    </div>
    </section>
    </div>
  </section>

</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, class: "contents") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :limit %>
    <%= form.date_field :limit, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= todo.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Limit:</strong>
    <%= todo.limit %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this todo", todo, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this todo', edit_todo_path(todo), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/todos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Show this todo", @todo, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Todos</h1>
    <%= link_to 'New todo', new_todo_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="todos" class="min-w-full">
    <%= render @todos %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo %>

    <%= link_to 'Edit this todo', edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this todo', todo_path(@todo), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#new</h1>
  <p>Find me in app/views/users/new.html.erb</p>
</div>